package eosrpc

// Generated by https://quicktype.io

type TraceGetBlockResponse struct {
	ID           string        `json:"id"`
	Number       int64         `json:"number"`
	PreviousID   string        `json:"previous_id"`
	Status       string        `json:"status"`
	Timestamp    string        `json:"timestamp"`
	Producer     string        `json:"producer"`
	Transactions []Transaction `json:"transactions"`
}

type TraceTransaction struct {
	ID      string   `json:"id"`
	Actions []Action `json:"actions"`
}

type TraceAction struct {
	GlobalSequence int64                  `json:"global_sequence"`
	Receiver       string                 `json:"receiver"`
	Account        string                 `json:"account"`
	Action         string                 `json:"action"`
	Authorization  []Authorization        `json:"authorization"`
	Data           map[string]interface{} `json:"data"`
}
